### ISSUE TITLE
Bulletproofing the async requirement

### ISSUE THREAD

**Issue by domenic** [promises-aplus/promises-spec#139]
Previous discussions in https://github.com/promises-aplus/promises-spec/issues/84#issuecomment-15694567, #70, and #100.
### Requirements

All of these _must_ call `a`, then `b`, then `c`.

``` js
// (Basic)
var p = new Promise(resolve => resolve())
a();
p.then(c);
b();
```

``` js
// (Resolve-Before-Then)
var resolveP;
var p = new Promise(resolve => resolveP = resolve);

a();
resolveP();
p.then(c);
b();
```

``` js
// (Resolve-After-Then)
var resolveP;
var p = new Promise(resolve => resolveP = resolve);

a();
p.then(c);
resolveP();
b();
```

``` js
// (Then-Inside-Then)
fulfilledP.then(function a() {
    fulfilledP.then(c);
    b();
});
```

This _should be allowed to_ call `a` then `b` then `c`:

``` js
// (Resolve-Inside-Async)
var p = new Promise(resolve => setImmediate(() => {
  a();
  resolve();
  c();
}));

p.then(b);
```

Naive implementations would probably do `a` then `c` then `b`, but because we are inside a `setImmediate`, it is at least one turn after `p.then(b)` occured, so it should be OK for `resolve()` to call `b` synchronously, in between `a` and `c`.
### The Situation

Currently, the spec's wording is:

> `then` must return before `onFulfilled` or `onRejected` is called

This is correct for (Basic), (Resolve-Before-Then), (Then-Inside-Then), and (Resolve-Inside-Async), but _incorrect_ for (Resolve-After-Then).
### The Goal

**Can anyone figure out phrasing that will be correct for all cases?**

**Comment by alexbyk** [comment]
even if this issue is old and closed, could you please edit top comment for Resolve-Inside-Async case?
Because if someone encounters this, he'll think that it should be a,b,c (instead of a,c,b)
