### ISSUE TITLE
Can onFulfilled and onRejected can be called multiple times?

### ISSUE THREAD

**Issue by lygstate** [promises-aplus/promises-spec#185]
onRejected  + onRejected  = 1?

**Comment by bergus** [comment]
No, they cannot. The spec explicitly states

> When fulfilled/rejected, a promise must not transition to any other state.

and 

> onFulfilled/onRejected must not be called more than once.

**Comment by briancavalier** [comment]
@lygstate Closing, since @bergus answered.  If you want to continue discussing, please feel free.
