### ISSUE TITLE
Include ES6 in the implementations list

### ISSUE THREAD

**Issue by bergus** [promises-aplus/promises-spec#211]
Given [this SO question](http://stackoverflow.com/questions/32553746/can-i-use-different-promise-implementations-together), maybe we should put ES6 Promises in our list of compatible implementations?

**Comment by briancavalier** [comment]
Seems like a great idea to me.  Perhaps it deserves a section all its own in the implementations page, above Standalone?

**Comment by domenic** [comment]
I pushed https://github.com/promises-aplus/promises-spec/commit/90a4116ca081af1b9e51b36e8074a6ab874e0932 that tries to make this clear. If you guys have suggested revisions feel free to let me know what you think or submit follow-up PRs.
